name: S3 and Lambda Deployment

on:
  push:
    branches: [ main ]

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      frontend_changed: ${{ steps.frontend_changes.outputs.frontend }}
      lambda_changed: ${{ steps.lambda_changes.outputs.lambda }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Check frontend changes
        id: frontend_changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            frontend: 'frontend/**'

      - name: Check lambda changes
        id: lambda_changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            lambda: 'lambda/**'

  deploy-frontend:
    needs: detect-changes
    if: needs.detect-changes.outputs.frontend_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Sync Frontend to S3
        run: aws s3 sync ./frontend s3://${{ secrets.S3_BUCKET }} --delete

  deploy-lambda:
    needs: detect-changes
    if: needs.detect-changes.outputs.lambda_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Zip Lambda Code
        run: zip -r lambda.zip ./lambda
      - name: Deploy Lambda
        run: aws lambda update-function-code --function-name ${{ secrets.LAMBDA_FUNCTION }} --zip-file fileb://lambda.zip
